[project]
name = 'clarity_conversions'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.SAT01_chatGPT]
path = 'contracts/SAT01_chatGPT.clar'
clarity_version = 2
epoch = 2.1

[contracts."SATPriceFeed.chatGPT"]
path = 'contracts/SATPriceFeed.chatGPT.clar'
clarity_version = 2
epoch = 2.1

[contracts.SATPriceFeed_chatGPT]
path = 'contracts/SATPriceFeed_chatGPT.clar'
clarity_version = 2
epoch = 2.1

[contracts.SATVault01_chatGPT]
path = 'contracts/SATVault01_chatGPT.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
